# -*- coding: utf-8 -*-
"""busquedasincrementales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wWeCaAM9s-Zfv36Wlvh9sI7LqZKCUHn1
"""

from sympy import *
import math

x = symbols("x")

def busquedas_incrementales(f, x0, step, n_max):
  x_prev = x0
  f_prev = f.subs(x, x_prev)
  x_now = x_prev + step
  f_now = f.subs(x, x_now)
  count = 0

  while f_prev*f_now>0 & count<n_max:
    count += 1
    x_prev = x_now
    f_prev = f_now
    x_now = x_now + step
    f_now = f.subs(x, x_now)

  return x_prev, x_now, count

f = x**2

busquedas_incrementales(f, -5, 0.5, 20)